### ISSUE TITLE
NICHES for spatial transcriptomic data 

### ISSUE THREAD

**Issue by chrkuo** [msraredon/NICHES#17]
Thank you for developing such a wonderful tool.

I am attempting to use NICHES on spatial transcriptomic data on Visium. 

I saw the vignette pasted here: (https://msraredon.github.io/NICHES/articles/01%20NICHES%20Spatial.html) 

I have a few questions:

**1. I am currently analyzing my spatial dataset through Giotto but it seems like NICHES utilizes Seurat. The vignette was not specific regarding where NICHES is utilized- is it after the deconvolution step after seurat? 

2. NICHES can be run on imputed or non-imputed data. - is this deconvoluted vs. non-deconvolved data? Do you have vignette on non-imputed data? 

3. it seems like niches output into an object and I have to scale/visualize and create UMAP again ?** 

Appreciate the assistance.

**Comment by chrkuo** [comment]
@msraredon any thoughts. 

Thank you

**Comment by chrkuo** [comment]
Hi @msraredon would appreciate your input

**Comment by msraredon** [comment]
NICHES can take any digital gene expression (DGE) matrix as input. For spatial, you can tell it to use designated x,y coordinates to limit cell crossings to either direct neighbors, k nearest neighbors, or a radius around each spot.

Imputation is different than deconvolution. Imputation attempts to reasonably fills in the zeros in the data. Deconvolution either provides a probability of a spot being a particular cell type, or splits each spot into multiple columns with each representing a guessed cell type, each of which will then be given the same XY coordinate I think. It depends on which package you are using and what the output looks like - I have not used deconvolution algorithms before.

I don't know if NICHES will allow multiple spots to have the same x,y coordinate -- I have never tried it with such data so I am not sure. @jcyang34 may know. If it doesn't we may want to look into this long-term.

But the bottom line is this: NICHES takes a DGE as input (does not need to be a Seurat object), and outputs cell-signaling matrices as outputs, which then need to be processed like any other single-cell matrix, in the package of your choice, in order to yield biological meaning.

 See this vignette for how to interface with other packages: https://msraredon.github.io/NICHES/articles/08%20Interoperability%20-%20NICHES.html

Hope this helps.
S

**Comment by chrkuo** [comment]
@msraredon thank you for this response! 

couple of questions: 
do you have actual documentation on how to specify radius around each spot to run NICHES on? it wasn't specifically stated on here for spatial data https://msraredon.github.io/NICHES/articles/01%20NICHES%20Spatial.html

In the spatial documentation: it is stated here "We can already see, from this plot, some notable overlap between the microenvironments of celltypes 1 & 7 and celltypes 6 & 3. Let’s explore this more deeply by finding signaling mechanisms specific to each celltype niche, plotting some of the results in heatmap form:" 

But i want to clarify - are these single cell - cell types? or just "spots." It's quite confusing because the documentation is for spatial transcriptomic dataset - the clustering is also at a spot level - unless this analysis for NICHES was done on seurat object that was integrated with scRNA seq data? 

Finally - is the output of NICHES for spatial transcriptomic at the resolution of spot level - essentially we still have to infer what cell types may be having this level of interaction but we can't 100% be certain because it's not a single cell level correcT?

Thank you
