### ISSUE TITLE
Analyzing scRNA-seq data with multiple treatment groups

### ISSUE THREAD

**Issue by scas224** [msraredon/NICHES#6]
Hi,
I have a scRNA-seq Seurat object with cells from six different treatment groups depending on age and time interval (meaning six different options for orig.ident). I am following the vignette 'Converting Single-Cell Atlases to Single-Cell Signaling Atlases' and I want to run NICHES on each treatment type subset so I can compare the results, but I am unsure whether to subset my Seurat object by orig.ident and run NICHES on each separately, or to run NICHES on the entire dataset together, and then subset the NICHES object by orig.ident. 

I have tried both methods and they yield very different results, so I was wondering which you would recommend?

**Comment by msraredon** [comment]
This is an excellent question, and one that we are being asked often. We are working on building a vignette to show how to best approach this task. I will addend this thread when it is posted.

In short: we recommend your first-mentioned approach. First, split your Seurat object by orig.ident, or similar metadata grouping by experimental condition. Then run NICHES on each object separately. These resulting NICHES outputs may then be tagged with appropriate metadata and then merged if you would like to analyze it collectively and perform differential or downstream analysis across groups.

Why this is important: As you mention, your two approaches will yield very different results. This is because NICHES works with all cells within an input dataset to sample and create cell-cell crosses. If cells from multiple experimental conditions are input together, cells will be crossed between conditions. For all biological applications we have encountered so far, this seems inappropriate to us. We therefore recommend either segregating cells by batch, or at least by experimental condition, prior to inputting into NICHES. The outputs may then be tagged and merged together after this initial step to yield a comprehensive dataset containing cell-cell signaling information which may be compared across experimental condition. (Segregating by experimental condition but not by batch often has the effect of 'smoothing' batch effects. Some users may consider this a reasonable approach.)

Let me know if this is not clear or how to help further. We will have a vignette online covering this soon.

S

**Comment by scas224** [comment]
This was very helpful, thank you so much! Looking forward to reading through that vignette soon!

**Comment by msraredon** [comment]
A vignette covering a version of this use case is now available here:
https://msraredon.github.io/NICHES/

Please let us know if further questions.

S
